# POST http://localhost:5000/apiv1/user/signup
# Content-Type: application/json

# { 
#     "firstName" : "AKSHAY",
#     "lastName" : "SINGH",
#     "email" : "akshaymel@gmail.com",
#     "username" : "akshaymemail",
#     "password" : "123456"
# }

# POST http://localhost:5000/apiv1/user/signin
# Content-Type: application/json

# { 
#     "email" : "akshayme@gmail.com",
#     "password" : "123456"
# }

  # POST http://localhost:5000/apiv1/client/save_session
  # Content-Type: application/json

  # {
  #     "session" : "123456789",
  #     "username":"akshaymemail"
  # }


# POST http://localhost:5000/apiv1/client/send_message
# Content-Type: application/json

# { 
#     "number" : "8271097843",
#     "message" : "hello",
#     "instanceid": "1",
#     "messageType":"text",
#     "media":"false"
# }

POST http://localhost:5000/apiv1/client/check_session
  Content-Type: application/json

  {
      "id":"1"
  }