# POST http://localhost:5000/api/user/signup
# Content-Type: application/json

# { 
#     "firstName" : "AKSHAY",
#     "lastName" : "SINGH",
#     "email" : "akshayme@gmail.com",
#     "username" : "akshaymemail",
#     "password" : "123456"
# }

POST http://localhost:5000/api/user/signin
Content-Type: application/json

{ 
    "email" : "akshayme@gmail.com",
    "password" : "123456"
}